const topLane = [
    { name: "Aatrox", img: "images/Top/aatrox.png" },
    { name: "Akali", img: "images/Top/akali.png" },
    { name: "Ambessa", img: "images/Top/ambessa.png" },
    { name: "Aurora", img: "images/Top/aurora.png" },
    { name: "Camille", img: "images/Top/camille.png" },
    { name: "Cho'Gath", img: "images/Top/chogath.png" },
    { name: "Darius", img: "images/Top/darius.png" },
    { name: "Fiora", img: "images/Top/fiora.png" },
    { name: "Gangplank", img: "images/Top/gangplank.png" },
    { name: "Garen", img: "images/Top/garen.png" },
    { name: "Gnar", img: "images/Top/gnar.png" },
    { name: "Gragas", img: "images/Top/gragas.png" },
    { name: "Gwen", img: "images/Top/gwen.png" },
    { name: "Heimerdinger", img: "images/Top/heimer.png" },
    { name: "Illaoi", img: "images/Top/illaoi.png" },
    { name: "Irelia", img: "images/Top/irelia.png" },
    { name: "Jax", img: "images/Top/jax.png" },
    { name: "Jayce", img: "images/Top/jayce.png" },
    { name: "Kayle", img: "images/Top/kayle.png" },
    { name: "Kennen", img: "images/Top/kennen.png" },
    { name: "Kled", img: "images/Top/kled.png" },
    { name: "K'Sante", img: "images/Top/ksante.png" },
    { name: "Malphite", img: "images/Top/malphite.png" },
    { name: "Mordekaiser", img: "images/Top/mordekaiser.png" },
    { name: "Dr.Mundo", img: "images/Top/mundo.png" },
    { name: "Naafiri", img: "images/Top/naafiri.png" },
    { name: "Nasus", img: "images/Top/nasus.png" },
    { name: "Olaf", img: "images/Top/olaf.png" },
    { name: "Pantheon", img: "images/Top/pantheon.png" },
    { name: "Poppy", img: "images/Top/poppy.png" },
    { name: "Quinn", img: "images/Top/quinn.png" },
    { name: "Renekton", img: "images/Top/renekton.png" },
    { name: "Riven", img: "images/Top/riven.png" },
    { name: "Rumble", img: "images/Top/rumble.png" },
    { name: "Sett", img: "images/Top/sett.png" },
    { name: "Shen", img: "images/Top/shen.png" },
    { name: "Singed", img: "images/Top/singed.png" },
    { name: "Sion", img: "images/Top/sion.png" },
    { name: "Tahm Kench", img: "images/Top/tahm.png" },
    { name: "Teemo", img: "images/Top/teemo.png" },
    { name: "Ornn", img: "images/Top/top_ornn.png" },
    { name: "Trundle", img: "images/Top/trundle.png" },
    { name: "Tryndamere", img: "images/Top/tryndamere.png" },
    { name: "Udyr", img: "images/Top/udyr.png" },
    { name: "Urgot", img: "images/Top/urgot.png" },
    { name: "Vayne", img: "images/Top/vayne.png" },
    { name: "Vladimir", img: "images/Top/vladimir.png" },
    { name: "Volibear", img: "images/Top/volibear.png" },
    { name: "Yasuo", img: "images/Top/yasuo.png" },
    { name: "Yone", img: "images/Top/yone.png" },
    { name: "Yorick", img: "images/Top/yorick.png" }
];

const jungleLane = [
    { name: "Amumu", img: "images/Jungle/amumu.png" },
    { name: "Bel'Veth", img: "images/Jungle/belveth.png" },
    { name: "Briar", img: "images/Jungle/briar.png" },
    { name: "Diana", img: "images/Jungle/diana.png" },
    { name: "Ekko", img: "images/Jungle/ekko.png" },
    { name: "Elise", img: "images/Jungle/elise.png" },
    { name: "Evelynn", img: "images/Jungle/evelynn.png" },
    { name: "Fiddlesticks", img: "images/Jungle/fiddlesticks.png" },
    { name: "Gragas", img: "images/Jungle/gragas.png" },
    { name: "Graves", img: "images/Jungle/graves.png" },
    { name: "Hecarim", img: "images/Jungle/hecarim.png" },
    { name: "Jarvan IV", img: "images/Jungle/jarvan.png" },
    { name: "Ivern", img: "images/Jungle/jgl_ivern.png" },
    { name: "Rammus", img: "images/Jungle/jgl_rammus.png" },
    { name: "Karthus", img: "images/Jungle/karthus.png" },
    { name: "Kayn", img: "images/Jungle/kayn.png" },
    { name: "Kha'Zix", img: "images/Jungle/khazix.png" },
    { name: "Kindred", img: "images/Jungle/kindred.png" },
    { name: "Lee Sin", img: "images/Jungle/leesin.png" },
    { name: "Lillia", img: "images/Jungle/lillia.png" },
    { name: "Master Yi", img: "images/Jungle/masteryi.png" },
    { name: "Nidalee", img: "images/Jungle/nidalee.png" },
    { name: "Nocturne", img: "images/Jungle/nocturne.png" },
    { name: "Nunu & Willump", img: "images/Jungle/nunu.png" },
    { name: "Pantheon", img: "images/Jungle/pantheon.png" },
    { name: "Rek'Sai", img: "images/Jungle/reksai.png" },
    { name: "Rengar", img: "images/Jungle/rengar.png" },
    { name: "Sejuani", img: "images/Jungle/sejuani.png" },
    { name: "Shaco", img: "images/Jungle/shaco.png" },
    { name: "Shyvana", img: "images/Jungle/shyvana.png" },
    { name: "Skarner", img: "images/Jungle/skarner.png" },
    { name: "Talon", img: "images/Jungle/talon.png" },
    { name: "Teemo", img: "images/Jungle/teemo.png" },
    { name: "Udyr", img: "images/Jungle/udyr.png" },
    { name: "Vi", img: "images/Jungle/vi.png" },
    { name: "Viego", img: "images/Jungle/viego.png" },
    { name: "Volibear", img: "images/Jungle/volibear.png" },
    { name: "Warwick", img: "images/Jungle/warwick.png" },
    { name: "Wukong", img: "images/Jungle/wukong.png" },
    { name: "Xin Zhao", img: "images/Jungle/xinzhao.png" },
    { name: "Zac", img: "images/Jungle/zac.png" }
];

const midLane = [
    { name: "Ahri", img: "images/Mid/ahri.png" },
    { name: "Akali", img: "images/Mid/akali.png" },
    { name: "Akshan", img: "images/Mid/akshan.png" },
    { name: "Anivia", img: "images/Mid/anivia.png" },
    { name: "Annie", img: "images/Mid/annie.png" },
    { name: "Aurora", img: "images/Mid/aurora.png" },
    { name: "Azir", img: "images/Mid/azir.png" },
    { name: "Cassiopeia", img: "images/Mid/cassiopeia.png" },
    { name: "Corki", img: "images/Mid/corki.png" },
    { name: "Diana", img: "images/Mid/diana.png" },
    { name: "Ekko", img: "images/Mid/ekko.png" },
    { name: "Fizz", img: "images/Mid/fizz.png" },
    { name: "Galio", img: "images/Mid/galio.png" },
    { name: "Hwei", img: "images/Mid/hwei.png" },
    { name: "Irelia", img: "images/Mid/irelia.png" },
    { name: "Jayce", img: "images/Mid/jayce.png" },
    { name: "Kassadin", img: "images/Mid/kassadin.png" },
    { name: "LeBlanc", img: "images/Mid/leblanc.png" },
    { name: "Lissandra", img: "images/Mid/lissandra.png" },
    { name: "Lux", img: "images/Mid/lux.png" },
    { name: "Malzahar", img: "images/Mid/malzahar.png" },
    { name: "Mel", img: "images/Mid/mel.png" },
    { name: "Katarina", img: "images/Mid/mid_katarina.png" },
    { name: "Naafiri", img: "images/Mid/naafiri.png" },
    { name: "Neeko", img: "images/Mid/neeko.png" },
    { name: "Orianna", img: "images/Mid/orianna.png" },
    { name: "Pantheon", img: "images/Mid/pantheon.png" },
    { name: "Qiyana", img: "images/Mid/qiyana.png" },
    { name: "Ryze", img: "images/Mid/ryze.png" },
    { name: "Smolder", img: "images/Mid/smolder.png" },
    { name: "Sol", img: "images/Mid/sol.png" },
    { name: "Swain", img: "images/Mid/swain.png" },
    { name: "Sylas", img: "images/Mid/sylas.png" },
    { name: "Syndra", img: "images/Mid/syndra.png" },
    { name: "Taliyah", img: "images/Mid/taliyah.png" },
    { name: "Talon", img: "images/Mid/talon.png" },
    { name: "Twisted Fate", img: "images/Mid/twisted.png" },
    { name: "Veigar", img: "images/Mid/veigar.png" },
    { name: "Vex", img: "images/Mid/vex.png" },
    { name: "Viktor", img: "images/Mid/viktor.png" },
    { name: "Vladimir", img: "images/Mid/vladimir.png" },
    { name: "Xerath", img: "images/Mid/xerath.png" },
    { name: "Yasuo", img: "images/Mid/yasuo.png" },
    { name: "Yone", img: "images/Mid/yone.png" },
    { name: "Zed", img: "images/Mid/zed.png" },
    { name: "Zoe", img: "images/Mid/zoe.png" }
];

const adcLane = [
    { name: "Aphelios", img: "images/ADC/aphelios.png" },
    { name: "Ashe", img: "images/ADC/ashe.png" },
    { name: "Caitlyn", img: "images/ADC/caitlyn.png" },
    { name: "Corki", img: "images/ADC/corki.png" },
    { name: "Draven", img: "images/ADC/draven.png" },
    { name: "Ezreal", img: "images/ADC/ezreal.png" },
    { name: "Jhin", img: "images/ADC/jhin.png" },
    { name: "Jinx", img: "images/ADC/jinx.png" },
    { name: "Kai'Sa", img: "images/ADC/kaisa.png" },
    { name: "Kalista", img: "images/ADC/kalista.png" },
    { name: "Kog'Maw", img: "images/ADC/kogmaw.png" },
    { name: "Lucian", img: "images/ADC/lucian.png" },
    { name: "Miss Fortune", img: "images/ADC/missfortune.png" },
    { name: "Nilah", img: "images/ADC/nilah.png" },
    { name: "Samira", img: "images/ADC/samira.png" },
    { name: "Sivir", img: "images/ADC/sivir.png" },
    { name: "Smolder", img: "images/ADC/smolder.png" },
    { name: "Tristana", img: "images/ADC/tristana.png" },
    { name: "Twitch", img: "images/ADC/twitch.png" },
    { name: "Varus", img: "images/ADC/varus.png" },
    { name: "Vayne", img: "images/ADC/vayne.png" },
    { name: "Xayah", img: "images/ADC/xayah.png" },
    { name: "Zeri", img: "images/ADC/zeri.png" },
    { name: "Ziggs", img: "images/ADC/ziggs.png" }
];

const supportLane = [
    { name: "Alistar", img: "images/Support/alistar.png" },
    { name: "Bard", img: "images/Support/bard.png" },
    { name: "Blitzcrank", img: "images/Support/blitzcrank.png" },
    { name: "Brand", img: "images/Support/brand.png" },
    { name: "Braum", img: "images/Support/braum.png" },
    { name: "Elise", img: "images/Support/elise.png" },
    { name: "Janna", img: "images/Support/janna.png" },
    { name: "Karma", img: "images/Support/karma.png" },
    { name: "Leona", img: "images/Support/leona.png" },
    { name: "Lulu", img: "images/Support/lulu.png" },
    { name: "Lux", img: "images/Support/lux.png" },
    { name: "Maokai", img: "images/Support/maokai.png" },
    { name: "Mel", img: "images/Support/mel.png" },
    { name: "Milio", img: "images/Support/milio.png" },
    { name: "Morgana", img: "images/Support/morgana.png" },
    { name: "Nami", img: "images/Support/nami.png" },
    { name: "Nautilus", img: "images/Support/nautilus.png" },
    { name: "Neeko", img: "images/Support/neeko.png" },
    { name: "Pantheon", img: "images/Support/pantheon.png" },
    { name: "Poppy", img: "images/Support/poppy.png" },
    { name: "Pyke", img: "images/Support/pyke.png" },
    { name: "Rakan", img: "images/Support/rakan.png" },
    { name: "Rell", img: "images/Support/rell.png" },
    { name: "Renata", img: "images/Support/renata.png" },
    { name: "Senna", img: "images/Support/senna.png" },
    { name: "Seraphine", img: "images/Support/seraphine.png" },
    { name: "Sona", img: "images/Support/sona.png" },
    { name: "Soraka", img: "images/Support/soraka.png" },
    { name: "Swain", img: "images/Support/swain.png" },
    { name: "Tahm Kench", img: "images/Support/tahm.png" },
    { name: "Taric", img: "images/Support/taric.png" },
    { name: "Thresh", img: "images/Support/thresh.png" },
    { name: "Vel'Koz", img: "images/Support/velkoz.png" },
    { name: "Xerath", img: "images/Support/xerath.png" },
    { name: "Yuumi", img: "images/Support/yuumi.png" },
    { name: "Zilean", img: "images/Support/zilean.png" },
    { name: "Zyra", img: "images/Support/zyra.png" }
];

